// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPa1xfvg9oeQy73VnhWdb49PGlk5gqBNU',
    appId: '1:1056061427970:android:c8e502b26c7fdbab70f21b',
    messagingSenderId: '1056061427970',
    projectId: 'sipiap-44f01',
    storageBucket: 'sipiap-44f01.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvoAcUrV8fKqu7U6rVVbNstv7h5XlZRRs',
    appId: '1:1056061427970:web:3e8405e543918e6170f21b',
    messagingSenderId: '1056061427970',
    projectId: 'sipiap-44f01',
    authDomain: 'sipiap-44f01.firebaseapp.com',
    storageBucket: 'sipiap-44f01.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAyH05ycOUzmT2XudGvQqxOeN8QxPUGQ2o',
    appId: '1:1056061427970:ios:a22ca21cd444c00a70f21b',
    messagingSenderId: '1056061427970',
    projectId: 'sipiap-44f01',
    storageBucket: 'sipiap-44f01.firebasestorage.app',
    iosBundleId: 'com.example.firebasePushNotification',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAyH05ycOUzmT2XudGvQqxOeN8QxPUGQ2o',
    appId: '1:1056061427970:ios:a22ca21cd444c00a70f21b',
    messagingSenderId: '1056061427970',
    projectId: 'sipiap-44f01',
    storageBucket: 'sipiap-44f01.firebasestorage.app',
    iosBundleId: 'com.example.firebasePushNotification',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCvoAcUrV8fKqu7U6rVVbNstv7h5XlZRRs',
    appId: '1:1056061427970:web:8756d4509a8cc2f770f21b',
    messagingSenderId: '1056061427970',
    projectId: 'sipiap-44f01',
    authDomain: 'sipiap-44f01.firebaseapp.com',
    storageBucket: 'sipiap-44f01.firebasestorage.app',
  );

}